import Foundation

struct QuizCatalog {
    static let allQuestions: [QuizQuestion] = [
        // ── Network Slicing ─────────────────────────────────────────────
        QuizQuestion(id: "q_ns_1", serviceId: "network_slicing", category: .coreConcepts, difficulty: .beginner, question: "What is S-NSSAI in 5G network slicing?", options: ["A subscriber identity", "Single Network Slice Selection Assistance Information", "A security algorithm", "Session management function"], correctIndex: 1, explanation: "S-NSSAI (Single NSSAI) identifies a network slice. It consists of SST (Slice/Service Type) and optional SD (Slice Differentiator).", reference: "TS 23.501 Section 5.15"),
        QuizQuestion(id: "q_ns_2", serviceId: "network_slicing", category: .architecture, difficulty: .intermediate, question: "Which NF is responsible for network slice selection in 5G Core?", options: ["SMF", "NSSF", "PCF", "UDM"], correctIndex: 1, explanation: "The NSSF (Network Slice Selection Function) selects the appropriate AMF set and allowed NSSAI for a UE based on subscription data and operator policies.", reference: "TS 23.501 Section 6.2.16"),
        QuizQuestion(id: "q_ns_3", serviceId: "network_slicing", category: .specifications, difficulty: .advanced, question: "In Rel-18, what does NSACF provide for network slicing?", options: ["Slice routing", "Network Slice Admission Control", "Slice-specific charging", "Slice mobility management"], correctIndex: 1, explanation: "NSACF (Network Slice Admission Control Function) controls the number of UEs/PDU sessions per slice to prevent overload and ensure SLA compliance.", reference: "TS 23.501 Section 6.2.18"),
        QuizQuestion(id: "q_ns_4", serviceId: "network_slicing", category: .latestDevelopments, difficulty: .expert, question: "What is the key Rel-19 enhancement for network slicing in SA2?", options: ["Slice-aware charging", "Hierarchical network slicing", "Slice-based handover", "Slice encryption"], correctIndex: 1, explanation: "Rel-19 introduces hierarchical slicing allowing sub-slices within a parent slice for finer-grained resource management and multi-tenant enterprise scenarios.", reference: "TR 23.700-41"),

        // ── SBA ─────────────────────────────────────────────────────────
        QuizQuestion(id: "q_sba_1", serviceId: "sba", category: .coreConcepts, difficulty: .beginner, question: "What protocol does the 5G SBI (Service Based Interface) use?", options: ["Diameter", "GTP-C", "HTTP/2", "SS7"], correctIndex: 2, explanation: "The 5G SBA uses HTTP/2 as the transport protocol for all service-based interfaces between NFs, replacing legacy Diameter and GTP-C.", reference: "TS 29.500"),
        QuizQuestion(id: "q_sba_2", serviceId: "sba", category: .architecture, difficulty: .intermediate, question: "What is the role of SCP in 5G SBA?", options: ["Subscriber data storage", "Service Communication Proxy for indirect routing", "Security Certificate Provider", "Session Control Point"], correctIndex: 1, explanation: "SCP (Service Communication Proxy) provides indirect communication, load balancing, topology hiding, and message routing between NFs on the SBI.", reference: "TS 23.501 Section 7.1.1"),
        QuizQuestion(id: "q_sba_3", serviceId: "sba", category: .protocols, difficulty: .advanced, question: "How does NRF-based NF discovery work in 5G SBA?", options: ["DNS-based lookup", "NF registers profile; consumers query NRF with parameters", "Broadcast-based discovery", "Static configuration file"], correctIndex: 1, explanation: "NFs register their NF Profile (capabilities, capacity, location) with NRF. Consumer NFs query NRF with discovery parameters (NF type, slice, locality) to find appropriate producer NFs.", reference: "TS 29.510"),
        QuizQuestion(id: "q_sba_4", serviceId: "sba", category: .latestDevelopments, difficulty: .expert, question: "What transport protocol is being studied for SBI in Rel-19?", options: ["gRPC", "HTTP/3 (QUIC)", "WebSocket", "MQTT"], correctIndex: 1, explanation: "SA2 is studying HTTP/3 (based on QUIC) for SBI to reduce latency, eliminate head-of-line blocking, and enable 0-RTT connection establishment.", reference: "SA2#163 discussion"),

        // ── UPF ─────────────────────────────────────────────────────────
        QuizQuestion(id: "q_upf_1", serviceId: "upf_userplane", category: .coreConcepts, difficulty: .beginner, question: "What is the primary function of UPF in 5G Core?", options: ["User authentication", "User plane packet forwarding and QoS enforcement", "Policy control", "Session management signaling"], correctIndex: 1, explanation: "UPF handles user plane data forwarding, QoS enforcement, traffic detection, usage reporting, and acts as the anchor point for PDU sessions.", reference: "TS 23.501 Section 6.2.3"),
        QuizQuestion(id: "q_upf_2", serviceId: "upf_userplane", category: .protocols, difficulty: .intermediate, question: "What protocol is used on the N4 interface between SMF and UPF?", options: ["GTP-U", "PFCP", "HTTP/2", "Diameter"], correctIndex: 1, explanation: "PFCP (Packet Forwarding Control Protocol) is used on N4 for SMF to provision forwarding rules (PDR, FAR, QER, URR) in the UPF.", reference: "TS 29.244"),
        QuizQuestion(id: "q_upf_3", serviceId: "upf_userplane", category: .architecture, difficulty: .advanced, question: "What is ULCL in the context of 5G UPF?", options: ["Uplink Channel Limitation", "Uplink Classifier for traffic steering to local/central DN", "User Location Control Layer", "Unified Link Control Logic"], correctIndex: 1, explanation: "ULCL (Uplink Classifier) is a UPF feature that steers traffic to different data networks (e.g., local edge vs central cloud) based on traffic detection rules.", reference: "TS 23.501 Section 5.6.4"),

        // ── NWDAF ───────────────────────────────────────────────────────
        QuizQuestion(id: "q_nwdaf_1", serviceId: "nwdaf", category: .coreConcepts, difficulty: .beginner, question: "What does NWDAF stand for?", options: ["Network Wireless Data Access Function", "Network Data Analytics Function", "Network Device Authentication Framework", "Node Workload Distribution and Forwarding"], correctIndex: 1, explanation: "NWDAF is the 3GPP-defined Network Data Analytics Function that provides network analytics and ML-based insights to other NFs and OAM.", reference: "TS 23.288"),
        QuizQuestion(id: "q_nwdaf_2", serviceId: "nwdaf", category: .architecture, difficulty: .intermediate, question: "What are the two logical functions of NWDAF in Rel-18?", options: ["Publisher and Subscriber", "MTLF and AnLF", "Training and Inference", "Collector and Reporter"], correctIndex: 1, explanation: "NWDAF is split into MTLF (Model Training Logical Function) for ML model training and AnLF (Analytics Logical Function) for analytics inference and reporting.", reference: "TS 23.288 Section 6.1"),
        QuizQuestion(id: "q_nwdaf_3", serviceId: "nwdaf", category: .latestDevelopments, difficulty: .expert, question: "What major AI technology is being integrated with NWDAF in Rel-19?", options: ["Computer Vision", "Large Language Models (LLM)", "Reinforcement Learning", "Generative Adversarial Networks"], correctIndex: 1, explanation: "Rel-19 NWDAF Phase 4 studies LLM integration for natural language network querying, automated root cause analysis, and intelligent network insights.", reference: "TR 23.700-80"),

        // ── NTN ─────────────────────────────────────────────────────────
        QuizQuestion(id: "q_ntn_1", serviceId: "ntn", category: .coreConcepts, difficulty: .beginner, question: "What does NTN stand for in 3GPP context?", options: ["New Transport Network", "Non-Terrestrial Networks", "Next-gen Topology Node", "Network Timing Notification"], correctIndex: 1, explanation: "NTN (Non-Terrestrial Networks) refers to satellite and HAPS-based communication systems integrated with terrestrial 5G/6G networks.", reference: "TR 38.811"),
        QuizQuestion(id: "q_ntn_2", serviceId: "ntn", category: .protocols, difficulty: .intermediate, question: "Why is HARQ typically disabled or modified for NTN?", options: ["Security concerns", "Excessive round-trip delay makes standard HARQ inefficient", "Insufficient bandwidth", "Incompatible modulation"], correctIndex: 1, explanation: "LEO satellites have 30-50ms RTT and GEO up to 600ms. Standard HARQ feedback timing is designed for terrestrial RTT (<1ms), making it impractical for NTN without modification.", reference: "TS 38.821"),
        QuizQuestion(id: "q_ntn_3", serviceId: "ntn", category: .latestDevelopments, difficulty: .advanced, question: "What is 'regenerative payload' in the context of NTN?", options: ["Self-healing antenna", "Satellite with on-board gNB processing capability", "Ground station power regeneration", "Spectrum recycling technology"], correctIndex: 1, explanation: "Regenerative payload means the satellite has on-board baseband processing (gNB-DU/CU), enabling it to decode/re-encode signals rather than just transparent relay.", reference: "SA2#163 NTN discussion"),

        // ── Edge Computing ──────────────────────────────────────────────
        QuizQuestion(id: "q_mec_1", serviceId: "edge_computing", category: .architecture, difficulty: .intermediate, question: "What is EASDF in 5G edge computing architecture?", options: ["Edge Application Server Discovery Function", "Enterprise Access Security Domain Function", "Edge Analytics and Storage Distribution Framework", "External API Service Delivery Framework"], correctIndex: 0, explanation: "EASDF (Edge Application Server Discovery Function) helps UEs discover the closest/best Edge Application Server using DNS-based mechanisms.", reference: "TS 23.548"),

        // ── ISAC ────────────────────────────────────────────────────────
        QuizQuestion(id: "q_isac_1", serviceId: "isac", category: .coreConcepts, difficulty: .intermediate, question: "What does ISAC combine?", options: ["Internet and Satellite Communication", "Integrated Sensing and Communication", "Internal Security and Access Control", "Intelligent Service Allocation and Configuration"], correctIndex: 1, explanation: "ISAC (Integrated Sensing and Communication) uses communication signals for radar-like sensing capabilities, enabling joint communication and environmental awareness.", reference: "TR 22.837"),
        QuizQuestion(id: "q_isac_2", serviceId: "isac", category: .latestDevelopments, difficulty: .advanced, question: "What sensing modes are defined in 3GPP ISAC study?", options: ["Active and Passive only", "Mono-static, bi-static, and multi-static", "Near-field and far-field", "Line-of-sight only"], correctIndex: 1, explanation: "3GPP defines mono-static (same Tx/Rx), bi-static (separate Tx and Rx), and multi-static (multiple distributed Tx/Rx) sensing modes for ISAC.", reference: "TR 22.837"),

        // ── Zero Trust ──────────────────────────────────────────────────
        QuizQuestion(id: "q_zt_1", serviceId: "zero_trust", category: .coreConcepts, difficulty: .beginner, question: "What is the core principle of Zero Trust Architecture?", options: ["Trust but verify", "Never trust, always verify", "Trust internal, verify external", "Verify once, trust forever"], correctIndex: 1, explanation: "Zero Trust means no entity (inside or outside the network) is trusted by default. Every access request must be authenticated, authorized, and encrypted.", reference: "NIST SP 800-207"),
        QuizQuestion(id: "q_zt_2", serviceId: "zero_trust", category: .specifications, difficulty: .intermediate, question: "How is NF authorization implemented on 5G SBI?", options: ["API key", "OAuth 2.0 access tokens via NRF", "Basic authentication", "IP whitelisting"], correctIndex: 1, explanation: "NFs use OAuth 2.0 access tokens issued by NRF to authorize service requests on the SBI. Each token specifies allowed NF services and scope.", reference: "TS 33.501, TS 29.510"),

        // ── NEF/CAPIF ───────────────────────────────────────────────────
        QuizQuestion(id: "q_ne_1", serviceId: "network_exposure", category: .architecture, difficulty: .intermediate, question: "What is CAPIF in 3GPP?", options: ["Core Access Point Interface Function", "Common API Framework for service API exposure", "Centralized Authentication and Policy Integration Function", "Cloud Application Platform Integration Framework"], correctIndex: 1, explanation: "CAPIF (Common API Framework) provides a unified framework for publishing, discovering, authenticating, and managing service APIs exposed to third-party applications.", reference: "TS 23.222"),
        QuizQuestion(id: "q_ne_2", serviceId: "network_exposure", category: .latestDevelopments, difficulty: .advanced, question: "What is CAMARA in the context of network APIs?", options: ["A 3GPP working group", "GSMA/LF project for operator-agnostic open network APIs", "A MEC platform vendor", "Camera-based sensing API"], correctIndex: 1, explanation: "CAMARA is a GSMA and Linux Foundation initiative creating standardized, operator-agnostic APIs (QoD, Location, Slicing) that map to 3GPP NEF/CAPIF capabilities.", reference: "camaraproject.org"),

        // ── Digital Twin ────────────────────────────────────────────────
        QuizQuestion(id: "q_dt_1", serviceId: "digital_twin", category: .coreConcepts, difficulty: .intermediate, question: "What is the primary purpose of a Network Digital Twin?", options: ["Backup network for failover", "Virtual replica for simulation, prediction, and testing", "Redundant control plane", "Mirror site for disaster recovery"], correctIndex: 1, explanation: "A Network Digital Twin is a virtual replica of the physical network used for what-if simulation, predictive maintenance, and risk-free testing of configuration changes.", reference: "ITU-T Y.3090"),

        // ── RIS ─────────────────────────────────────────────────────────
        QuizQuestion(id: "q_ris_1", serviceId: "ris", category: .coreConcepts, difficulty: .intermediate, question: "What is a Reconfigurable Intelligent Surface?", options: ["A type of antenna array", "Programmable metasurface that manipulates RF signal propagation", "A software-defined radio interface", "Adaptive modulation technique"], correctIndex: 1, explanation: "RIS is a planar surface with many low-cost elements that can be electronically controlled to reflect, refract, or absorb RF signals, creating smart radio environments.", reference: "TR 38.858"),

        // ── Semantic Comms ──────────────────────────────────────────────
        QuizQuestion(id: "q_sem_1", serviceId: "semantic_comms", category: .coreConcepts, difficulty: .advanced, question: "How does semantic communication differ from traditional (Shannon) communication?", options: ["Uses different modulation", "Transmits meaning/intent rather than raw bits", "Operates on different frequencies", "Requires quantum channels"], correctIndex: 1, explanation: "Semantic communication goes beyond Shannon's bit-level paradigm by transmitting the meaning or intent of information using AI-based semantic codecs, achieving extreme compression.", reference: "IEEE Comm Surveys 2024"),

        // ── Cross-Service Advanced Questions ─────────────────────────────
        QuizQuestion(id: "q_cross_1", serviceId: "sba", category: .protocols, difficulty: .expert, question: "In 5G SBA, what happens when NRF is unreachable during NF discovery?", options: ["All services stop immediately", "SCP uses cached NF profiles for local discovery", "UEs are redirected to 4G", "Emergency mode activates satellite backup"], correctIndex: 1, explanation: "When NRF is unreachable, SCP maintains cached NF profiles and can perform local service discovery and load balancing based on last-known NF status.", reference: "TS 29.500, TS 23.501"),
        QuizQuestion(id: "q_cross_2", serviceId: "nwdaf", category: .architecture, difficulty: .expert, question: "How does federated learning work across multiple NWDAFs?", options: ["Each NWDAF shares raw data with others", "NWDAFs train local models and share only model parameters/gradients", "A central NWDAF trains on all data", "ML is not supported across NWDAFs"], correctIndex: 1, explanation: "Federated learning in NWDAF allows multiple NWDAFs to collaboratively train ML models by sharing only model updates (gradients/parameters), preserving data privacy.", reference: "TS 23.288 Rel-18"),
        QuizQuestion(id: "q_cross_3", serviceId: "upf_userplane", category: .architecture, difficulty: .expert, question: "In a multi-UPF PDU session with ULCL, how does SMF decide traffic steering rules?", options: ["UE requests specific UPF", "SMF uses AF-influenced traffic routing and local DN configuration to provision PDRs in ULCL UPF", "Random load balancing", "Based on UE IP address only"], correctIndex: 1, explanation: "SMF provisions Packet Detection Rules (PDRs) in the ULCL UPF based on AF traffic influence (via NEF/PCF), local DN configuration, and operator policy to steer traffic to edge or central UPF.", reference: "TS 23.501 Section 5.6.4, TS 29.244"),
    ]

    static func questions(for serviceId: String? = nil, category: QuizCategory? = nil, difficulty: QuizDifficulty? = nil) -> [QuizQuestion] {
        var filtered = allQuestions
        if let serviceId { filtered = filtered.filter { $0.serviceId == serviceId } }
        if let category { filtered = filtered.filter { $0.category == category } }
        if let difficulty { filtered = filtered.filter { $0.difficulty == difficulty } }
        return filtered
    }

    static func randomQuiz(count: Int = 10, serviceId: String? = nil, category: QuizCategory? = nil) -> [QuizQuestion] {
        let pool = questions(for: serviceId, category: category)
        return Array(pool.shuffled().prefix(count))
    }
}
